export const TAMIL_NADU_LOCATIONS = {
  "Ariyalur": ["Ariyalur", "Andimadam", "Sendurai", "Udayarpalayam"],
  "Chengalpattu": ["Chengalpattu", "Cheyyur", "Madhurantakam", "Pallavaram", "Tambaram", "Thirukalukundram", "Thirupporur", "Vandalur"],
  "Chennai": ["Alandur", "Ambattur", "Aminjikarai", "Ayanavaram", "Egmore", "Guindy", "Madhavaram", "Maduravoyal", "Mambalam", "Mylapore", "Perambur", "Purasawalkam", "Sholinganallur", "Thiruvottiyur", "Tondiarpet", "Velachery"],
  "Coimbatore": ["Coimbatore North", "Coimbatore South", "Annur", "Madukkarai", "Mettupalayam", "Perur", "Pollachi", "Sulur", "Valparai"],
  "Cuddalore": ["Cuddalore", "Bhuvanagiri", "Chidambaram", "Kattumannarkoil", "Kurinjipadi", "Panruti", "Srimushnam", "Titakudi", "Veppur", "Vriddhachalam"],
  "Dharmapuri": ["Dharmapuri", "Harur", "Karimangalam", "Nallampalli", "Palacode", "Pappireddipatti", "Pennagaram"],
  "Dindigul": ["Dindigul East", "Dindigul West", "Attur", "Gujiliamparai", "Kodaikanal", "Natham", "Nilakottai", "Oddanchatram", "Palani", "Reddiarchatram", "Shanarpatty", "Vedasandur"],
  "Erode": ["Erode", "Anthiyur", "Bhavani", "Gobichettipalayam", "Kodumudi", "Modakkurichi", "Nambiyur", "Perundurai", "Sathyamangalam", "Thalavadi"],
  "Kallakurichi": ["Kallakurichi", "Chinnasalem", "Kalvarayan Hills", "Sankarapuram", "Tirukkoilur", "Ulundurpet"],
  "Kanchipuram": ["Kanchipuram", "Kundrathur", "Sriperumbudur", "Uthiramerur", "Walajabad"],
  "Kanyakumari": ["Agastheeswaram", "Kalkulam", "Killiyoor", "Thiruvattar", "Thovalai", "Vilavancode"],
  "Karur": ["Karur", "Aravakurichi", "Kadavur", "Krishnarayapuram", "Kulithalai", "Manmangalam", "Pugalur"],
  "Krishnagiri": ["Krishnagiri", "Anchetty", "Bargur", "Denkanikottai", "Hosur", "Pochampalli", "Shoolagiri", "Uthangarai"],
  "Madurai": ["Madurai East", "Madurai North", "Madurai South", "Madurai West", "Melur", "Peraiyur", "Thirumangalam", "Thiruparankundram", "Usilampatti", "Vadipatti"],
  "Mayiladuthurai": ["Mayiladuthurai", "Kuthalam", "Sirkazhi", "Tharangambadi"],
  "Nagapattinam": ["Nagapattinam", "Kilvelur", "Thirukkuvalai", "Vedaranyam"],
  "Namakkal": ["Namakkal", "Kabilarmalai", "Kollihills", "Paramathi Velur", "Rasipuram", "Senthamangalam", "Thiruchengodu"],
  "Nilgiris": ["Udhagamandalam", "Coonoor", "Gudalur", "Kotagiri", "Kundah", "Pandalur"],
  "Perambalur": ["Perambalur", "Alathur", "Kunnam", "Veppanthattai"],
  "Pudukkottai": ["Pudukkottai", "Alangudi", "Aranthangi", "Avudaioarkoil", "Gandarvakottai", "Karambakudi", "Kulathur", "Illuppur", "Manamelkudi", "Ponnamaravathi", "Thirumayam"],
  "Ramanathapuram": ["Ramanathapuram", "Kadaladi", "Kamuthi", "Keelakarai", "Mudukulathur", "Paramakudi", "Rameswaram", "Tiruvadanai"],
  "Ranipet": ["Ranipet", "Arakkonam", "Arcot", "Kalavai", "Nemili", "Sholinghur", "Walajah"],
  "Salem": ["Salem", "Attur", "Edappadi", "Gangavalli", "Kadayampatti", "Mettur", "Omalur", "Pethanaickenpalayam", "Sankari", "Valapady", "Yercaud"],
  "Sivagangai": ["Sivagangai", "Devakottai", "Ilayangudi", "Kalayarkoil", "Karaikudi", "Manamadurai", "Singampunari", "Tiruppathur", "Tirupuvanam"],
  "Tenkasi": ["Tenkasi", "Alangulam", "Kadayanallur", "Sankarankovil", "Shenkottai", "Sivagiri", "Thiruvengadam", "Veerakeralamputhur"],
  "Thanjavur": ["Thanjavur", "Boothalur", "Kumbakonam", "Orathanadu", "Papanasam", "Pattukottai", "Peravurani", "Thiruvaiyaru", "Thiruvidaimarudur"],
  "Theni": ["Theni", "Andipatti", "Bodinayakanur", "Periyakulam", "Uthamapalayam"],
  "Thoothukudi": ["Thoothukudi", "Ettayapuram", "Kovilpatti", "Ottapidaram", "Sathankulam", "Srivaikuntam", "Tiruchendur", "Vilathikulam"],
  "Tiruchirappalli": ["Tiruchirappalli East", "Tiruchirappalli West", "Lalgudi", "Manachanallur", "Manapparai", "Musiri", "Srirangam", "Thiruverumbur", "Thottiyam", "Thuraiyur"],
  "Tirunelveli": ["Tirunelveli", "Ambasamudram", "Cheranmahadevi", "Manur", "Nanguneri", "Palayamkottai", "Radhapuram", "Thisayanvilai"],
  "Tirupattur": ["Tirupattur", "Ambur", "Natrampalli", "Vaniyambadi"],
  "Tiruppur": ["Tiruppur North", "Tiruppur South", "Avinashi", "Dharapuram", "Kangeyam", "Madathukulam", "Palladam", "Udumalaipettai", "Uthukuli"],
  "Tiruvallur": ["Tiruvallur", "Avadi", "Gummidipoondi", "Ponneri", "Poonamallee", "R.K. Pet", "Pallipattu", "Tiruttani", "Uthukottai"],
  "Tiruvannamalai": ["Tiruvannamalai", "Arni", "Chengam", "Chetpet", "Cheyyar", "Jamunamarathur", "Kalasapakkam", "Polur", "Vandavasi", "Vembakkam"],
  "Tiruvarur": ["Tiruvarur", "Kudavasal", "Mannargudi", "Nannilam", "Needamangalam", "Thiruthuraipoondi", "Valangaiman"],
  "Vellore": ["Vellore", "Anaicut", "Gudiyatham", "Katpadi", "Pernambut"],
  "Viluppuram": ["Viluppuram", "Gingee", "Kandachipuram", "Marakkanam", "Melmalayanur", "Merkanam", "Vikravandi", "Vanur"],
  "Virudhunagar": ["Virudhunagar", "Aruppukottai", "Kariyapatti", "Rajapalayam", "Sattur", "Sivakasi", "Srivilliputhur", "Tiruchuli", "Watrap"]
};
